export const PRESETS = {
  pad: {
    name: 'Warm Pad',
    osc1Type: 'sine',
    osc2Type: 'sine',
    detune: 6,
    osc2FreqMult: 1,
    filterFreq: 1100,
    filterQ: 0.4,
    attack: 0.025,
    decay: 0.4,
    sustainLevel: 0.38,
  },
  ePiano: {
    name: 'E. Piano',
    osc1Type: 'triangle',
    osc2Type: 'sine',
    detune: 3,
    osc2FreqMult: 1,
    filterFreq: 2200,
    filterQ: 0.6,
    attack: 0.008,
    decay: 0.5,
    sustainLevel: 0.18,
  },
  organ: {
    name: 'Organ',
    osc1Type: 'sine',
    osc2Type: 'sine',
    detune: 2,
    osc2FreqMult: 2, // adds second harmonic
    filterFreq: 1800,
    filterQ: 0.3,
    attack: 0.01,
    decay: 0.05,
    sustainLevel: 0.92,
  },
  strings: {
    name: 'Strings',
    osc1Type: 'sawtooth',
    osc2Type: 'sawtooth',
    detune: 12,
    osc2FreqMult: 1,
    filterFreq: 650,
    filterQ: 1.0,
    attack: 0.18,
    decay: 0.5,
    sustainLevel: 0.72,
  },
  bells: {
    name: 'Bells',
    osc1Type: 'sine',
    osc2Type: 'triangle',
    detune: 1,
    osc2FreqMult: 1,
    filterFreq: 4000,
    filterQ: 1.2,
    attack: 0.004,
    decay: 1.2,
    sustainLevel: 0.04,
  },
  pluck: {
    name: 'Pluck',
    osc1Type: 'triangle',
    osc2Type: 'sine',
    detune: 8,
    osc2FreqMult: 1,
    filterFreq: 900,
    filterQ: 2.0,
    attack: 0.003,
    decay: 0.25,
    sustainLevel: 0.08,
  },
}
